# Generated by Django 4.2.16 on 2025-06-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0005_remove_information_faireundon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='recevoirInfo',
            field=models.CharField(max_length=250),
        ),
    ]
