# Generated by Django 4.2.16 on 2025-06-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0008_alter_information_recevoirinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='nom',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='telephone',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
