# Generated by Django 4.2.16 on 2025-06-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0009_alter_information_nom_alter_information_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='nom',
            field=models.CharField(max_length=250),
        ),
    ]
