# Generated by Django 4.2.16 on 2025-06-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0010_alter_information_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='invitation',
            field=models.ImageField(default=1, storage='media/invitation_send', upload_to=''),
            preserve_default=False,
        ),
    ]
