# Generated by Django 4.2.16 on 2025-06-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0011_information_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='invitation',
        ),
    ]
