# Generated by Django 4.2.16 on 2025-06-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0012_remove_information_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='recevoirInfo',
            new_name='recevoir',
        ),
    ]
